package com.kyowon.sms.wells.web.closing.sales.dto;

import javax.validation.constraints.NotBlank;

import io.swagger.annotations.ApiModel;

public class WdcbSalesConfirmCreateDto {
    @ApiModel(value = "WdcbSalesConfirmCreateDto-CreateReq")
    public record CreateReq(
        @NotBlank
        String cntrNo,
        @NotBlank
        int cntrSn,
        String slRcogDt,
        String kwGrpCdCd,
        String bzHdqDvCd,
        String ogTpCd,
        String prtnrNo,
        String pdHclsfId,
        String pdMclsfId,
        String pdLclsfId,
        String pdCd,
        String cstNo,
        String copnDvCd,
        String bzrno,
        String sellTpCd,
        String sellTpDtlCd,
        String sellInflwChnlDtlCd,
        int sellQty,
        int sellAmt,
        int sellAmtVat,
        int sellSplAmt,
        int cntrTam,
        int subscAmt,
        int rentalRgstCost,
        int rentalAmt,
        int rentalDscAmt,
        int rentalPtrm,
        int rentalTn,
        int istmPcamAmt,
        int istmFeeLvyAmt,
        int istmAmt,
        int istmMcn,
        int mmIstmAmt,
        int dscAmt,
        int cntramDpAmt,
        int bilDscAmt,
        int ovrCtrDpAmt,
        int prmTn,
        int totPrmAmt,
        int prmExpAmt,
        String prmStrtY,
        String prmStrtMm,
        String prmEndY,
        String prmEndMm,
        int prmMcn,
        int prmDscr,
        int prmDscAmt,
        int prmDpAmt,
        int prmRfndAmt,
        int prmRplcAmt,
        int prmSlAmt,
        int nomSlAmt,
        int spmtSlAmt,
        int nomDscAmt,
        int spmtDscAmt,
        int slCtrAmt,
        int slCanAmt,
        String slStpYn,
        String cntrStlmFshDtm,
        String cntrStrtdt,
        String canDt,
        int slDc,
        int svAmt,
        int nomIntAmt,
        int mlgSlAmt,
        String ostrDtm,
        String sppDtm,
        String istDtm,
        String reqdDtm,
        String svDt,
        int pvdaOjPcam,
        int pvdaAmt,
        String slRcogClsfCd,
        String lgstItmGdCd,
        int reimPcsvCs,
        int pcsvReimAmt,
        String iostDt,
        int slQty,
        String rtngdYn,
        String frisuYn,
        String fgptYn
    ) {}
}
