server:
    port: 8080
    profile: local

sflex:
    file:
        path:
            root: c:\nas\gatch
            attachFile: \appdata\attachfile
            temp: ${sflex.file.path.attachFile}\temp
            export: ${sflex.file.path.attachFile}\export
    drm:
        path:
            temp: c:\nas\drm\temp\
    authentication:
        passwordCheck: false
    authorization:
        dataServiceIdCheck:
            ignoreApi: all
        #      ignoreApi: /api/v1/common/security/login,/api/v1/common/pages,/api/v1/common/meta,/api/v1/common/portal
        pageRoleCheck: false
        dataServiceRoleCheck: false
        cors:
            accessControlAllowOrigin: "*"
    logging:
        login: true
        page: false
        dataService: false
        menu: false
        exception: true
    tableHistory:
        realtime: false
    query:
        maxSize: 5000
    sap:
        rfcDirectApi: /api/v1/common/rfc-direct
    firebase:
        privateKey:
            wells: wells-db99d-firebase-adminsdk-z35j0-eb65330c08.json
    sso:
        use: false
    cubeone:
        useYn: N
    aes:
        secretKey: KSTATION-ENC-DEV-KEY-2023-195817

portal:
    defaultId: WEB_ADM
    login:
        simple:
            enabled: true
            url: http://localhost:8080/certification/{portal-id}/simpleLogin.html
        default:
            url: http://localhost:8080/certification/main
        welcome:
            enabled: true
            url: http://localhost:8080/certification/welcome.html
    ssoLogout:
        url: http://localhost:8080/certification/sso/sso-service?pname=spLogout
    main:
        url: http://localhost:3000/

spring:
    devtools:
        restart:
            exclude: mybatis/sql/**/*.xml
    output:
        ansi:
            enabled: always
    redis:
        database: 1
        sentinelHost:
            server1: 10.1.199.5
            server2: 10.1.199.5
            server3: 10.1.199.5
        sentinelPort:
            server1: 5300
            server2: 5301
            server3: 5302
        password: 'OtLKsonzcHIHGAbpOico781K'
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 2
        ttl: 60

webClient:
    proxy:
        host: d-orvp.kyowon.co.kr
        port: 8111
    cruzlink: http://10.1.25.21:49001
    eai: http://d-eai.kyowon.co.kr:10001/mediate/KYOWON
    sujiewon: https://api.sujiewon.com:18015/nrasrv
    controlm: https://d-ctm.kyowon.co.kr:8446/automation-api

controlm:
    ctm: ctmkwda01
    userId: apiuser
    password: empass

kworks:
    message:
        apikey: FLOW_BOT_NOTI_API
        botcert: 20220209-7ee5a72f-0229-48b7-8e64-91ade9c37a53
        botid: noti_kstation

kakaopay:
    callbackUrl: http://localhost:8080/api/v1/interface/sflex/common/common/kakaopay

datasource:
    ########### DEV #######################
    pri:
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbcUrl: jdbc:log4jdbc:oracle:thin:@//10.1.60.29:1515/DITGKW
        username: WSMDEV
        password: WSM#DEV1249##
        maximumpoolsize: 10
        auto-commit: false
        cacheprepstmts: true
        prepstmtcachesize: 250
        prepstmtcachesqlLimit: 2048
    sec:
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbcUrl: jdbc:log4jdbc:oracle:thin:@//10.1.60.29:1515/DITGKW
        username: WSMDEV
        password: WSM#DEV1249##
        maximumpoolsize: 10
        auto-commit: false
        cacheprepstmts: true
        prepstmtcachesize: 250
        prepstmtcachesqlLimit: 2048

############## LOGGING Setting ############
logging:
    level:
        root: info
        com.sds: debug
        com.kyowon: debug
        com.sds.sflex.system.config.filter.LoggingFilter: off
        org.mybatis: error
        jdbc.sqlonly: off
        jdbc.sqltiming: info
        jdbc.audit: error
        jdbc.resultset: off
        jdbc.resultsettable: off
        jdbc.connection: off
        org.thymeleaf: error
