server:
    port: 8080
    profile: local

sflex:
    file:
        path:
            root: c:\nas\gatch
            attachFile: \appdata\attachfile
            temp: ${sflex.file.path.attachFile}\temp
            export: ${sflex.file.path.attachFile}\export
            gsm: c:\nas\gsm
    drm:
        path:
            temp: c:\nas\drm\temp\
    authentication:
        passwordCheck: true
        dupLoginCheck: false
    authorization:
        dataServiceIdCheck:
            ignoreApi: all
        #      ignoreApi: /api/v1/common/security/login,/api/v1/common/pages,/api/v1/common/meta,/api/v1/common/portal
        pageRoleCheck: false
        dataServiceRoleCheck: false
        cors:
            accessControlAllowOrigin: "*"
    logging:
        login: true
        page: false
        dataService: false
        menu: false
        exception: true
    tableHistory:
        realtime: false
    query:
        maxSize: 5000
    sap:
        rfcDirectApi: /api/v1/common/rfc-direct
    firebase:
        privateKey:
            wells: wells-db99d-firebase-adminsdk-z35j0-eb65330c08.json
    sso:
        use: false
    cubeone:
        useYn: N
        useProd: false
    aes:
        secretKey: KSTATION-ENC-DEV-KEY-2023-195817

portal:
    defaultId: WEB_DEF
    login:
        simple:
            enabled: true
            url: http://localhost:8080/certification/{portal-id}/simpleLogin.html
        default:
            url: http://localhost:8080/certification/main
        welcome:
            enabled: true
            url: http://localhost:8080/certification/welcome.html
    ssoLogout:
        url: http://localhost:8080/certification/sso/sso-service?pname=spLogout
    main:
        url: http://localhost:3000/
    ssoInit:
        url: https://d-sso.kyowon.co.kr/api/kyowon/user/pwInit

spring:
    devtools:
        restart:
            exclude: mybatis/sql/**/*.xml
    output:
        ansi:
            enabled: always
    redis:
        database: 1
        sentinelHost: 10.1.199.5,10.1.199.37,10.1.199.38
        sentinelPort: 5100,5100,5100
        password: 'OtLKsonzcHIHGAbpOico781K'
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 2
        ttl: 60

webClient:
    proxy:
        host: d-rvp.kyowon.co.kr
        port: 8111
    cruzlink: http://d-fep.kyowon.co.kr:49001
    eai: http://d-eai.kyowon.co.kr:10001/mediate/KYOWON
    sujiewon: https://api.sujiewon.com:18015/nrasrv
    controlm: https://d-ctm.kyowon.co.kr:8446/automation-api
    kakaoMobility: https://apis-navi.kakaomobility.com/v1/directions

report:
    ozUrl: https://d-eform.kyowon.co.kr:2943

nice:
    url: https://d-nskey.kyowon.co.kr

controlm:
    ctm: ctmkwda01
    userId: dqapiuser
    password: FckNsvd5JyqWnX7HhS5ny3NsBOtoJ52W

kworks:
    message:
        apikey: FLOW_BOT_NOTI_API
        botcert: 20220209-7ee5a72f-0229-48b7-8e64-91ade9c37a53
        botid: noti_kstation

kportal:
    approval:
        url: https://kportal.digitalkyowon.com/KyowonGroupwareLogin.aspx
        secretKey: 2022-0217-KSPL-KFLW-000000

kakaopay:
    callbackUrl: http://localhost:8081/api/v1/interface/sflex/common/common/kakaopay

kakaosync:
    home: https://kstagent.kyowon.co.kr:4311

datasource:
    ########### DEV #######################
    pri:
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbcUrl: jdbc:log4jdbc:oracle:thin:@//10.1.60.29:1515/DITGKW
        username: WSMDEV
        password: WSM#DEV1249##
        maximumpoolsize: 10
        auto-commit: false
        cacheprepstmts: true
        prepstmtcachesize: 250
        prepstmtcachesqlLimit: 2048
    custsvc:
        name: 'customerServiceCenter'
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbcUrl: jdbc:log4jdbc:oracle:thin:@//10.1.60.29:1515/DITGKW
        username: CCSIFA
        password: CCS#IFA1249##
        maximumpoolsize: 10
        auto-commit: false
        cacheprepstmts: true
        prepstmtcachesize: 250
        prepstmtcachesqlLimit: 2048
    kportal:
        name: 'kportal'
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbcUrl: jdbc:sqlserver://10.1.30.195:3950;DatabaseName=Kportal_ezBoardSTD
        username: ekpboard
        password: ekp!23
        maximumpoolsize: 10
        auto-commit: false
        cacheprepstmts: true
        prepstmtcachesize: 250
        prepstmtcachesqlLimit: 2048
        initialSize: 2
        maxTotal: 30
        maxIdle: 10
        minIdle: 3
        maxWaitMillis: 30000
        removeAbandonedOnMaintenance: true
        removeAbandonedTimeout: 30
        validationQuery: SELECT 1

############## LOGGING Setting ############
logging:
    level:
        root: info
        com.sds: debug
        com.kyowon: debug
        com.sds.sflex.system.config.filter.LoggingFilter: off
        org.mybatis: error
        jdbc.sqlonly: off
        jdbc.sqltiming: info
        jdbc.audit: error
        jdbc.resultset: off
        jdbc.resultsettable: off
        jdbc.connection: off
        org.thymeleaf: error
