server:
    port: 8890

sflex:
    file:
        path:
            physical: /wsmwlq_sdata/qa/appdata
            temp: ${sflex.file.path.physical}/temp/
            export: ${sflex.file.path.physical}/export/
    drm:
        path:
            temp: /drmkwq_sdata/qa/appdata/temp/
    authentication:
        passwordCheck: false
    authorization:
        dataServiceIdCheck:
            ignoreApi: all
        #      ignoreApi: /api/v1/common/security/login,/api/v1/common/pages,/api/v1/common/meta,/api/v1/common/portal
        pageRoleCheck: false
        dataServiceRoleCheck: false
        cors:
            accessControlAllowOrigin: https://q-wsm.kyowon.co.kr,https://q-sso.kyowon.co.kr,https://q-osso.kyowon.co.kr
    logging:
        login: true
        page: false
        dataService: false
        menu: true
        exception: true
    tableHistory:
        realtime: false
    query:
        maxSize: 5000
    sap:
        rfcDirectApi: /api/v1/common/rfc-direct
    firebase:
        privateKey:
            wells: wells-db99d-firebase-adminsdk-z35j0-eb65330c08.json
    sso:
        use: false
    cubeone:
        useYn: Y

portal:
    defaultId: WEB_ADM
    login:
        simple:
            enabled: true
            url: /certification/{portal-id}/simpleLogin.html
        default:
            url: /certification/main
        welcome:
            enabled: true
            url: /certification/welcome.html
    ssoLogout:
        url: /certification/sso/sso-service?pname=spLogout
    main:
        url: /#

spring:
    devtools:
        restart:
            exclude: mybatis/sql/**/*.xml
    output:
        ansi:
            enabled: never
    database: 0
    redis:
        database: 1
        sentinelHost:
            server1: 10.1.199.5
            server2: 10.1.199.5
            server3: 10.1.199.5
        sentinelPort:
            server1: 5800
            server2: 5801
            server3: 5802
        password: 'DvCATdWb97MHBeMeTwtCiQWm'
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 2
        ttl: 60
webClient:
    proxy:
        host: d-orvp.kyowon.co.kr
        port: 8111
    cruzlink: http://10.1.25.21:49001
    eai: http://10.1.199.7:10001/mediate/KYOWON
    sujiewon: https://api.sujiewon.com:18015/nrasrv
    controlm: https://ctmkwqa01:8446/automation-api

controlm:
    ctm: ctmkwqa01
    userId: apiuser
    password: empass

kakaopay:
    callbackUrl: https://q-wsm.kyowon.co.kr/api/v1/interface/sflex/common/common/kakaopay

datasource:
    ########### QA #######################
    jndi:
        use: true
    pri:
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jndi-name: 'java:/DS-QITGKW1-NXA'
    sec:
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jndi-name: 'java:/DS-QITGKW1-NXA'

############## LOGGING Setting ############
logging:
    file:
        path: ${jboss.server.log.dir}
    config: classpath:logback-kyowon.xml
    level:
        root: info
        com.sds: debug
        org.mybatis: error
        jdbc.sqlonly: debug
        jdbc.sqltiming: error
        jdbc.audit: error
        jdbc.resultset: error
        jdbc.resultsettable: error
        jdbc.connection: error
        org.thymeleaf: error
