package com.kyowon.sms.wells.web.contract.ordermgmt.dto;

import javax.validation.constraints.NotBlank;

import io.swagger.annotations.ApiModel;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class WctaOrderDetailInqrDto {

    @ApiModel(value = "WctaOrderDetailInqrDto-SearchReq")
    public record SearchReq(
        @NotBlank
        String searchGbn,
        String bryyMmdd,
        String bzrno,
        String sexGbn,
        String cstKnm,
        String cralLocaraTno,
        String cntrCstNo,
        String cntrCanYn
    ) {}
    @ApiModel(value = "WctaOrderDetailInqrDto-SearchRes")
    public record SearchRes(
        String cntrDtlNo,
        String cntrNo,
        String cntrSn,
        String cstKnm,
        String copnDvCd,
        String copnDvNm,
        String bzrno,
        String bryyMmdd,
        String sexDvCd,
        String rnmno,
        String rnmnoDvCd,
        String rnmnoEncr,
        String basePdCd,
        String basePdNm,
        String dscApyTpCd,
        String dscApyTpNm,
        String dscApyDtlCd,
        String dscApyDtlNm,
        String cntrRcpFshDtm,
        String sppDuedt,
        String slDt,
        String cntrCanDt,
        String cpsDt,
        String slPasgDt,
        String slCnfmYn,
        String cntrCanRsonCd,
        String canRsonNm,
        String cntrChDtlRsonCd,
        String cntrChDtlRsonNm,
        String frisuYn,
        String freExpnCnfmDtm,
        String cttTpCd,
        String cttTpNm,
        String iostDtlCd,
        String sppIvcCrtDtm,
        String booSellYn,
        String cntrTpCd,
        String cntrTpNm,
        String sellPrtnrNm,
        String fstRgstUsrId,
        String fstRgstDeptId,
        String rveCd,
        String uswyDv,
        String svPrd,
        String frisuAsPtrmN,
        String frisuBfsvcPtrmN,
        String recapMshYn,
        String alncmpNm,
        String sellEvCd,
        String sellEvNm,
        String fnlAmt,
        String sellAmt,
        String vat,
        String cntrAmt,
        String istmIntAmt,
        String feeAckmtBaseAmt,
        String crpUc,
        String totDscAmt,
        String feeAckmtCt,
        String ackmtPerfAmt,
        String feeAckmtTotAmt,
        String feeFxamYn,
        String pdSaleFee,
        String cashBlam,
        String istmMcn,
        String mmIstmAmt,
        String istmPcamAmt,
        String cntrCstNo,
        String cralLocaraTno,
        String mexnoEncr,
        String cralIdvTno,
        String newAdrZip,
        String rnadr,
        String rdadr,
        String rcgvpKnm,
        String istlcCralLocaraTno,
        String istlcMexnoEncr,
        String istlcCralIdvTno,
        String istlcAdrZip,
        String istlcAdr,
        String istlcDadr,
        String cntrRelDtlNm,
        String alncmpCntrDrmVal,
        String alncmpCd,
        String alncPrtnrDrmVal,
        String spcOrdDv,
        String sppOrdIvcNo,
        String basePdInfo,
        String basePdCd2,
        String pdQty,
        String fgptPdNm1,
        String fgptPdNm2,
        String fgptPdNm3,
        String fgptPdNm4,
        String bfsvcBzsDvCd,
        String bfsvcBzsDvNm,
        String splyBzsDvCd,
        String splyBzsDvNm,
        String cntrCanDtm
    ) {}
}
