package com.kyowon.sms.wells.web.contract.ordermgmt.rest;

import com.kyowon.sms.wells.web.contract.ordermgmt.dto.WctaReceiptBulkUploadDto.CreateProspectCstReq;
import com.kyowon.sms.wells.web.contract.ordermgmt.dto.WctaReceiptBulkUploadDto.ValidateReq;
import com.kyowon.sms.wells.web.contract.ordermgmt.dto.WctaReceiptBulkUploadDto.ValidateRes;
import com.kyowon.sms.wells.web.contract.ordermgmt.service.WctaReceiptBulkUploadService;
import com.kyowon.sms.wells.web.contract.zcommon.constants.CtContractConst;
import com.sds.sflex.system.config.response.SaveResponse;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import lombok.RequiredArgsConstructor;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Api(tags = "[WCTA] 주문상세페이지 내부 팝업_세금계산서, 계산서")
@Validated
@RequiredArgsConstructor
@RestController
@RequestMapping(CtContractConst.REST_URL_V1 + "/bulk-upload")
public class WctaReceiptBulkUploadController {

    private final WctaReceiptBulkUploadService service;

    @ApiOperation(
        value = "주소 정제",
        notes = "상세 주소 기준으로 수지원넷에 요청하고 정제된 주소 정보를 조회 한다. 화면에서 조용히 실행하기 위해 biz exception 으로 감싸 rethrow 한다. 굳이 put 으로 한건 멱등성을 강조하기 위함이렸다."
    )
    @PutMapping({"/prospects/validate"})
    public ValidateRes validateProspects(@RequestBody ValidateReq req) {
        return service.validateProspects(req);
    }

    @ApiOperation(value = "가망고객 등록", notes = "generated by LT")
    @PostMapping("/prospects")
    public SaveResponse createProspectCsts(
        @RequestBody
        List<CreateProspectCstReq> reqs
    ) {
        return SaveResponse.builder().processCount(service.createProspectCsts(reqs)).build();
    }


}
