package com.kyowon.sms.wells.web.closing.performance.dvo;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class WdccMonthlySalesClosingAggregationDvo {
    private String slClYm; //
    private String cntrNo; //
    private String cntrSn; //
    private String kwGrpCoCd; //
    private String bzHdqDvCd; //
    private String pdCd; //
    private String svPrd; //
    private String cstNo; //
    private String sellTpCd; //
    private String sellTpDtlCd; //
    private String sellInflwChnlDtlCd; //
    private String sapPdDvCd; //
    private String ogTpCd; //
    private String prtnrNo; //
    private String sellQty; //
    private String sellAmt; //
    private String sellAmtVat; //
    private String cntrTam; //
    private String rentalRgstCost; //
    private String rentalRgstCostDfam; //
    private String rentalRgstCostVat; //
    private String rentalAmtDfam; //
    private String rentalAmt; //
    private String rentalDscAmt; //
    private String cntrPtrm; //
    private String svAmt; //
    private String rentalAmt2; //
    private String rentalDscAmt2; //
    private String rentalPtrm2; //
    private String frisuBfsvcPtrmN; //
    private String dscDfamAmt; //
    private String cntrAmt; //
    private String cntramDpAmt; //
    private String cntramDfam; //
    private String crpUcAmt; //
    private String istmPcamAmt; //
    private String istmFeeLvyAmt; //
    private String istmAmt; //
    private String istmMcn; //
    private String mmIstmAmt; //
    private String dscAmt; //
    private String rentalTn; //
    private String sppTn; //
    private String slQty; //
    private String rentalDc; //
    private String slDc; //
    private String nomSlAmt; //
    private String spmtSlAmt; //
    private String nomDscAmt; //
    private String spmtDscAmt; //
    private String slCtrAmt; //
    private String thmSlSumAmt; //
    private String slSumVat; //
    private String slAggAmt; //
    private String dscAggAmt; //
    private String pvdaAmt; //
    private String intVat; //
    private String pvdaAggAmt; //
    private String thmOcSvSlAmt; //
    private String thmOcSvSlVat; //
    private String thmOcSvSlAggAmt; //
    private String leaseSlCtrAmt; //
    private String leaseSlCanAmt; //
    private String leaseSlCtrTotAmt; //
    private String chQty; //
    private String slChAmt; //
    private String chVat; //
    private String canQty; //
    private String slCanAmt; //
    private String canVat; //
    private String thmOcFeeAmt; //
    private String thmIntamDpAmt; //
    private String thmIstmRfndAmt; //
    private String thmIstmTotDpAmt; //
    private String btdAtam; //
    private String thmAtamDpAmt; //
    private String thmAtamRfndAmt; //
    private String atamRplcProcsAmt; //
    private String ovrCtrDpAmt; //
    private String prpdSlAmt; //
    private String slBndAlrpyAmt; //
    private String slDpAggAmt; //
    private String eotAtam; //
    private String btdSvAmt; //
    private String svDpAmt; //
    private String svRfndAmt; //
    private String eotSvAmt; //
    private String btdUcAmt; //
    private String eotUcAmt; //
    private String eotPcamBlam; //
    private String eotPcamIntBlam; //
    private String btdBilUcAmt; //
    private String thmBilOcAmt; //
    private String thmBilDpAmt; //
    private String thmBilCtrAmt; //
    private String thmBilSpmtAmt; //
    private String eotBilUcAmt; //
    private String nmnBilUcExpAmt; //
    private String slStpYn; //
    private String slStpAmt; //
    private String prmTn; //
    private String prmMcn; //
    private String prmDpAmt1; //
    private String prmPtrmMcn1; //
    private String prmDpAmt2; //
    private String prmPtrmMcn2; //
    private String totPrmAmt; //
    private String prmExpAmt; //
    private String prmStrtYm; //
    private String prmEndYm; //
    private String prmDscr; //
    private String prmDscAmt; //
    private String prmBlamBtdAmt; //
    private String prmDpAmt; //
    private String prmRfndAmt; //
    private String prmRplcAmt; //
    private String prmSlAmt; //
    private String prmBlamEotAmt; //
    private String mlgBtdPrpdAmt; //
    private String mlgDpAmt; //
    private String mlgRfndAmt; //
    private String mlgSlAmt; //
    private String mlgEotPrpdAmt; //
    private String cntrDt; //
    private String sppDtm; //
    private String istDtm; //
    private String canDt; //
    private String reqdDtm; //
    private String svDt; //
    private String slRcogDt; //
    private String fulpyDt; //
    private String dtaDlYn; //
    private String tsmBilUcExpAmt; //
    private String subscAmt; //
    private String prmChYn; //
}
