package com.kyowon.sms.wells.web.bond.consultation.dto;

import io.swagger.annotations.ApiModel;

public class WbncContractDto {

    @ApiModel(value = "WbncContractDto-SearchReq")
    public record SearchReq(
        String schClctamNo,
        String schCstNm,
        String schDlqMcntStrt,
        String schDlqMcntEnd,
        String schIstTno,
        String schCntrNo,
        String schCstNo,
        String schBizDv,
        String schIstMpno,
        String schTno,
        String schSfK,
        String schCstDv,
        String schOjBlamStrt,
        String schOjBlamEnd,
        String schMpno,
        String schTfDtStrt,
        String schTfDtEnd,
        String schFntDv,
        String schFntDtStrt,
        String schFntDtEnd,
        String schBilDv,
        String schCstThmDp,
        String schAuthRsgYn,
        String schDv
    ) {}

    @ApiModel(value = "WbncContractDto-SearchRes")
    public record SearchRes(
        String ctt,
        String bizDv,
        String prdf,
        String pdctNm,
        String cntrNo,
        String cntrSn,
        String cstNm,
        String dlqMcnt,
        String ojAmt,
        String ojDp,
        String ojBlam,
        String totDlqAmt,
        String totDlqDp,
        String totDlqBlam,
        String dlqAmt,
        String dlqDp,
        String dlqBlam,
        String mmChramAmt,
        String mmChramDp,
        String mmChramBlam,
        String dlqAddAmt,
        String dlqAddDp,
        String dlqAddBlam,
        String ucAmt,
        String ucDp,
        String ucBlam,
        String totDpAmt,
        String spmtSl,
        String ccam,
        String lsfe,
        String rtlfe1,
        String rtlfeIstm1,
        String rtlfe2,
        String rtlfeIstm2,
        String promDt,
        String dprNm,
        String cvcpInf,
        String clctamIchr,
        String cntrMpno,
        String cntrTno,
        String istMpno,
        String istTno,
        String cstNo,
        String tfDt,
        String buNotiDt,
        String buNotiTp,
        String cntrZip,
        String cntrAdr,
        String istZip,
        String istAdr,
        String vtAcBnk,
        String vtAcno,
        String pesuDt,
        String hiDt,
        String ovrdDt,
        String cpsnEfcm,
        String dsbCmd,
        String prtyClrs,
        String submCmd,
        String crcCmd,
        String cujOvrd,
        String vstRs,
        String vstDt,
        String sfk,
        String unuitm
    ) {}

}
